export const KEYBOARD_KEYS = {
  //ROW 1 -------------------
  Backquote: getLetterKey("ё", "Ё", "`", "~"),
  Digit1: getLetterKey("1", "!", "1", "!"),
  Digit2: getLetterKey("2", '"', "2", "@"),
  Digit3: getLetterKey("3", "№", "3", "#"),
  Digit4: getLetterKey("4", ";", "4", "$"),
  Digit5: getLetterKey("5", "%", "5", "%"),
  Digit6: getLetterKey("6", ":", "6", "^"),
  Digit7: getLetterKey("7", "?", "7", "&"),
  Digit8: getLetterKey("8", "*", "8", "*"),
  Digit9: getLetterKey("9", "(", "9", "("),
  Digit0: getLetterKey("0", ")", "0", ")"),
  Minus: getLetterKey("-", "_", "-", "_"),
  Equal: getLetterKey("=", "+", "=", "+"),
  Backspace: getSystemKey("Backspace", ["key--backspace", "key--flex"]),
  //ROW 2 -------------------
  Tab: getSystemKey("Tab", ["key--tab", "key--flex"]),
  KeyQ: getLetterKey("й", "Й", "q", "Q"),
  KeyW: getLetterKey("ц", "Ц", "w", "W"),
  KeyE: getLetterKey("у", "У", "e", "E"),
  KeyR: getLetterKey("к", "К", "r", "R"),
  KeyT: getLetterKey("е", "Е", "t", "T"),
  KeyY: getLetterKey("н", "Н", "y", "Y"),
  KeyU: getLetterKey("г", "Г", "u", "U"),
  KeyI: getLetterKey("ш", "Ш", "i", "I"),
  KeyO: getLetterKey("щ", "Щ", "o", "O"),
  KeyP: getLetterKey("з", "З", "p", "P"),
  BracketLeft: getLetterKey("х", "{", "[", "{"),
  BracketRight: getLetterKey("ъ", "Ъ", "]", "}"),
  Backslash: getLetterKey("\\", "/", "\\", "|"),
  Delete: getSystemKey("Del", ["key--del", "key--flex"]),
  //ROW 3 -------------------
  CapsLock: getSystemKey("CapsLock", ["key--caps", "key--flex"]),
  KeyA: getLetterKey("ф", "Ф", "a", "A"),
  KeyS: getLetterKey("ы", "Ы", "s", "S"),
  KeyD: getLetterKey("в", "В", "d", "D"),
  KeyF: getLetterKey("а", "А", "f", "F"),
  KeyG: getLetterKey("п", "П", "g", "G"),
  KeyH: getLetterKey("р", "Р", "h", "H"),
  KeyJ: getLetterKey("о", "О", "j", "J"),
  KeyK: getLetterKey("л", "Л", "k", "K"),
  KeyL: getLetterKey("д", "Д", "l", "L"),
  Semicolon: getLetterKey("ж", "Ж", ";", ":"),
  Quote: getLetterKey("э", "Э", "'", '"'),
  Enter: getSystemKey("Enter", ["key--enter", "key--flex"]),
  //ROW 4 -------------------
  ShiftLeft: getSystemKey("Shift", ["key--shift", "key--flex"]),
  KeyZ: getLetterKey("я", "Я", "z", "Z"),
  KeyX: getLetterKey("ч", "Ч", "x", "X"),
  KeyC: getLetterKey("с", "С", "c", "C"),
  KeyV: getLetterKey("м", "М", "v", "V"),
  KeyB: getLetterKey("и", "И", "b", "B"),
  KeyN: getLetterKey("т", "Т", "n", "N"),
  KeyM: getLetterKey("ь", "Ь", "m", "M"),
  Comma: getLetterKey("б", "Б", ",", '<"'),
  Period: getLetterKey("ю", "Ю", ".", ">"),
  Slash: getLetterKey(".", ",", "/", "?"),
  ArrowUp: getLetterKey("▲", "▲", "▲", "▲"),
  ShiftRight: getSystemKey("Shift", ["key--shift", "key--flex"]),
  //ROW 5 -------------------
  ControlLeft: getSystemKey("Ctrl", ["key--ctrl"]),
  MetaLeft: getSystemKey("Win", ["key--shift", "key--flex"]),
  AltLeft: getSystemKey("Alt", ["key--alt", "key--flex"]),
  Space: getSystemKey("Space", ["key--space"]),
  AltRight: getSystemKey("Alt", ["key--alt", "key--flex"]),
  ArrowLeft: getLetterKey("◄", "◄", "◄", "◄"),
  ArrowDown: getLetterKey("▼", "▼", "▼", "▼"),
  ArrowLRight: getLetterKey("►", "►", "►", "►"),
  ControlRight: getSystemKey("Ctrl", ["key--ctrl"]),
};

export const KEYBOARD_LAYOUT = [
  [
    //ROW 1 -------------------
    "Backquote",
    "Digit1",
    "Digit2",
    "Digit3",
    "Digit4",
    "Digit5",
    "Digit6",
    "Digit7",
    "Digit8",
    "Digit9",
    "Digit0",
    "Minus",
    "Equal",
    "Backspace",
  ],
  [
    //ROW 2 -------------------
    "Tab",
    "KeyQ",
    "KeyW",
    "KeyE",
    "KeyR",
    "KeyT",
    "KeyY",
    "KeyU",
    "KeyI",
    "KeyO",
    "KeyP",
    "BracketLeft",
    "BracketRight",
    "Backslash",
    "Delete",
  ],
  [
    //ROW 3 -------------------
    "CapsLock",
    "KeyA",
    "KeyS",
    "KeyD",
    "KeyF",
    "KeyG",
    "KeyH",
    "KeyJ",
    "KeyK",
    "KeyL",
    "Semicolon",
    "Quote",
    "Enter",
  ],
  [
    //ROW 4 -------------------
    "ShiftLeft",
    "KeyZ",
    "KeyX",
    "KeyC",
    "KeyV",
    "KeyB",
    "KeyN",
    "KeyM",
    "Comma",
    "Period",
    "Slash",
    "ArrowUp",
    "ShiftRight",
  ],
  [
    //ROW 5 -------------------
    "ControlLeft",
    "MetaLeft",
    "AltLeft",
    "Space",
    "AltRight",
    "ArrowLeft",
    "ArrowDown",
    "ArrowLRight",
    "ControlRight",
  ],
];

function getSystemKey(text, additionalClasses) {
  return {
    text: text,
    additionalClasses: additionalClasses,
    systemKey: true,
  };
}

function getLetterKey(ruText, ruShiftText, enText, enShiftText) {
  return {
    ru: { text: ruText, shiftText: ruShiftText },
    en: { text: enText, shiftText: enShiftText },
    letterKey: true,
  };
}
