export const KEYBOARD_KEYS = {
  // ROW 1 -------------------
  Backquote: ["ё", "Ё", "`", "~", "letter"],
  Digit1: ["1", "!", "1", "!", "letter"],
  Digit2: ["2", "\"", "2", "@", "letter"],
  Digit3: ["3", "№", "3", "#", "letter"],
  Digit4: ["4", ";", "4", "$", "letter"],
  Digit5: ["5", "%", "5", "%", "letter"],
  Digit6: ["6", ":", "6", "^", "letter"],
  Digit7: ["7", "?", "7", "&", "letter"],
  Digit8: ["8", "*", "8", "*", "letter"],
  Digit9: ["9", "(", "9", "(", "letter"],
  Digit0: ["0", ")", "0", ")", "letter"],
  Minus: ["-", "_", "-", "_", "letter"],
  Equal: ["=", "+", "=", "+", "letter"],
  Backspace: ["Backspace", ["key--flex"], "system"],
  // ROW 2 -------------------
  Tab: ["Tab", ["key--tab", "key--flex"], "system"],
  KeyQ: ["й", "Й", "q", "Q", "letter"],
  KeyW: ["ц", "Ц", "w", "W", "letter"],
  KeyE: ["у", "У", "e", "E", "letter"],
  KeyR: ["к", "К", "r", "R", "letter"],
  KeyT: ["е", "Е", "t", "T", "letter"],
  KeyY: ["н", "Н", "y", "Y", "letter"],
  KeyU: ["г", "Г", "u", "U", "letter"],
  KeyI: ["ш", "Ш", "i", "I", "letter"],
  KeyO: ["щ", "Щ", "o", "O", "letter"],
  KeyP: ["з", "З", "p", "P", "letter"],
  BracketLeft: ["х", "{", "[", "{", "letter"],
  BracketRight: ["ъ", "Ъ", "]", "}", "letter"],
  Backslash: ["\\", "/", "\\", "|", "letter"],
  Delete: ["Del", ["key--flex"], "system"],
  // ROW 3 -------------------
  CapsLock: ["CapsLock", ["key--caps", "key--flex"], "system"],
  KeyA: ["ф", "Ф", "a", "A", "letter"],
  KeyS: ["ы", "Ы", "s", "S", "letter"],
  KeyD: ["в", "В", "d", "D", "letter"],
  KeyF: ["а", "А", "f", "F", "letter"],
  KeyG: ["п", "П", "g", "G", "letter"],
  KeyH: ["р", "Р", "h", "H", "letter"],
  KeyJ: ["о", "О", "j", "J", "letter"],
  KeyK: ["л", "Л", "k", "K", "letter"],
  KeyL: ["д", "Д", "l", "L", "letter"],
  Semicolon: ["ж", "Ж", ";", ":", "letter"],
  Quote: ["э", "Э", "'", "\"", "letter"],
  Enter: ["Enter", ["key--flex"], "system"],
  // ROW 4 -------------------
  ShiftLeft: ["Shift", ["key--flex"], "system"],
  KeyZ: ["я", "Я", "z", "Z", "letter"],
  KeyX: ["ч", "Ч", "x", "X", "letter"],
  KeyC: ["с", "С", "c", "C", "letter"],
  KeyV: ["м", "М", "v", "V", "letter"],
  KeyB: ["и", "И", "b", "B", "letter"],
  KeyN: ["т", "Т", "n", "N", "letter"],
  KeyM: ["ь", "Ь", "m", "M", "letter"],
  Comma: ["б", "Б", ",", "<", "letter"],
  Period: ["ю", "Ю", ".", ">", "letter"],
  Slash: [".", ",", "/", "?", "letter"],
  ArrowUp: ["▲", "▲", "▲", "▲", "letter"],
  ShiftRight: ["Shift", ["key--flex"], "system"],
  // ROW 5 -------------------
  ControlLeft: ["Ctrl", [], "system"],
  MetaLeft: ["Win", ["key--flex"], "system"],
  AltLeft: ["Alt", ["key--flex"], "system"],
  Space: ["Space", ["key--space"], "system"],
  AltRight: ["Alt", ["key--flex"], "system"],
  ArrowLeft: ["◄", "◄", "◄", "◄", "letter"],
  ArrowDown: ["▼", "▼", "▼", "▼", "letter"],
  ArrowRight: ["►", "►", "►", "►", "letter"],
  ControlRight: ["Ctrl", [], "system"],
};

export const KEYBOARD_LAYOUT = [
  [
    // ROW 1 -------------------
    "Backquote",
    "Digit1",
    "Digit2",
    "Digit3",
    "Digit4",
    "Digit5",
    "Digit6",
    "Digit7",
    "Digit8",
    "Digit9",
    "Digit0",
    "Minus",
    "Equal",
    "Backspace",
  ],
  [
    // ROW 2 -------------------
    "Tab",
    "KeyQ",
    "KeyW",
    "KeyE",
    "KeyR",
    "KeyT",
    "KeyY",
    "KeyU",
    "KeyI",
    "KeyO",
    "KeyP",
    "BracketLeft",
    "BracketRight",
    "Backslash",
    "Delete",
  ],
  [
    // ROW 3 -------------------
    "CapsLock",
    "KeyA",
    "KeyS",
    "KeyD",
    "KeyF",
    "KeyG",
    "KeyH",
    "KeyJ",
    "KeyK",
    "KeyL",
    "Semicolon",
    "Quote",
    "Enter",
  ],
  [
    // ROW 4 -------------------
    "ShiftLeft",
    "KeyZ",
    "KeyX",
    "KeyC",
    "KeyV",
    "KeyB",
    "KeyN",
    "KeyM",
    "Comma",
    "Period",
    "Slash",
    "ArrowUp",
    "ShiftRight",
  ],
  [
    // ROW 5 -------------------
    "ControlLeft",
    "MetaLeft",
    "AltLeft",
    "Space",
    "AltRight",
    "ArrowLeft",
    "ArrowDown",
    "ArrowRight",
    "ControlRight",
  ],
];
